### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by githublukas** [SpinalCMS/bridgetown-docs-template#3]
Hi guys,

Love the theme and SpinalCMS but I can't seem to get this working though.

Followed the instructions. 
Also after adding the docs with the command "$ bundle add bridgetown-docs-template -g bridgetown_plugins" 
I see that it get's nicely added to the gem file but when I run the server the files don't get added to the project. 

What am I doing wrong?

**Comment by eelcoj** [comment]
It wasn't you. The version on Rubygems wasn't up-to-date. Just pushed a new version: https://rubygems.org/gems/bridgetown-docs-template

Also updated the README to include the step about adding the theme/plugin to your config/initializers.rb. 

There is currently some log output, I assume, around yarn; if you find the cause, please submit a PR. ✌️
